title: DarkWatch
description: A PoC demonstrating AI surveillance capabilities.
remote_theme: pages-themes/hacker@v0.2.0
baseurl: "/DarkWatch"
url: "https://ai-voodoo.github.io"
author: Jeff Sims

plugins:
  - jekyll-remote-theme
  - jekyll-feed

markdown: kramdown
